[project]
name = "NemaDB"
version = "1.3.0"
description = "NemaDB"
requires-python = ">=3.10"
dependencies = [
    "flet==1.0.1",
]

[tool.flet.app]
path = "."
module = "main"
exclude = [
    ".git",
    ".flet",
    ".venv",
    "__pycache__",
    "*.pyc",
    "build",
    "dist",
]

[tool.flet]
company = "NemaDB"
copyright = "Copyright (C) 2026 NemaDB"

[tool.flet.template]
# url = "./flet_build_template"

[tool.flet.build]
file_version = "1.3.0.0"
product_version = "1.3.0.0"
product_name = "NemaDB"
